### ISSUE TITLE
Problem running ANE on Android 7 or newer

### ISSUE THREAD

**Issue by sakariasliukko** [myflashlab/PDF-ANE#10]
## Environment ##
* Apache Flex Version: 4.16
* AIR SDK Version: 26

## Problem Description ##
PDF-ANE won't open files on Android 7 or newer. It works fine on Android 5 and 6.

**Comment by lami66** [comment]
I confirm, _ex.run(....) return false whithout dispatch PdfViewerEvent

My File is in a public folder and it exist

Why it does not display the application choice. That work on Android 5.1 but not Android 8.0

Your ANE is compatible Android 8?

**Comment by myflashlab** [comment]
well, we double checked and confirm that the ANE works on Android 7+ and 8+.
Let me guess, Are you using the permission ANE to ask for storage access before trying to open the pdf? Check the sample codes: https://github.com/myflashlab/PDF-ANE/blob/master/AIR/src/MainFinal.as#L155

**Comment by lami66** [comment]
I have checked my code and I check the permission for acces storage, a popup require permission but after when I run pdfViewer it return false whithout stateEvent.
I would like transmit you my test flex project, How can I do it?
my sdk is flex 4.16 AIR 29

**Comment by lami66** [comment]
this is the out logs 👍 trying to open pdf file: false
------------------
$ane = PDF_ANE
$class = AirCommand
$msg = Old intent updated
------------------
------------------
$ane = PDF_ANE
$class = AirCommand
$msg = file: /storage/emulated/0/test.pdf exists: true
------------------
_isDialogOpen = false
_currSource = null

**Comment by lami66** [comment]
finnaly that right now bcause I haved forgoten to add 

\<uses-sdk android:targetSdkVersion="23"/\>

inside android manifest in the application descriptor

**Comment by myflashlab** [comment]
Oh, I thought the issue was opened by @lami66 . @sakariasliukko please let us know if that fixed it for you also?

**Comment by lami66** [comment]
I am stupid, add use-sdk is not the solution but a shortcut to avoid the problem.
Because Google request to deploy application with sdk version min to 26.
I have tested with use-sdk on this version and that don't work!!!!!!!!!

**Comment by myflashlab** [comment]
@lami66 nice catch. The problem is that targetSDK 24+ do not allow the ```file://``` scheme like before and will through an error like this: 
```
exposed beyond app through Intent.getData()
```
we're on this to fix the problem. in the meanwhile, if you can have ```<uses-sdk android:targetSdkVersion="23"/>``` in your manifest, do that.

**Comment by myflashlab** [comment]
Ok, we have an update now. please download the latest ANE V2.2.0 from [here](). but before just replacing the ANE in your app, make sure you have read the [changelog](https://github.com/myflashlab/PDF-ANE/#changelog) and corrected your AS3 code and manifest settings accordingly.

We also confirm that with this update, it works fine not only on android targetSdkVersion 26, but also older versions will be fine.

If you are a club member and are using the [ANELAB](https://github.com/myflashlab/ANE-LAB/), just open up the software and update the ANE there. otherwise, you should wait until we get ready the packages for manual download.
