### ISSUE TITLE
ARM Errors during publish process in Animate CC2018 for AIR 26/28

### ISSUE THREAD

**Issue by gwmatthias** [myflashlab/PDF-ANE#11]
* AIR SDK Version: 26 and 28.0.0.125

I get multiple errors while publishing in Animate CC2018 for AIR 26/28 (iOS) regarding armv7 and arm64

![air_error_pdfviewer](https://user-images.githubusercontent.com/17932638/34485521-6a29f4c8-efcb-11e7-9924-31a629a1288d.png)

**Comment by myflashlab** [comment]
you are missing the dependency file... the overrideAIR.ane https://github.com/myflashlab/common-dependencies-ANE
