### ISSUE TITLE
Error #1009 with PDFViewer

### ISSUE THREAD

**Issue by stephanberger4** [myflashlab/PDF-ANE#12]
Hi, 

I've just bought the PDF Viewer ANE. I've implemented the ANE to my project (using Adobe Animate CC with Android AIR 28) and paste the example code given on Github : 

```
import com.myflashlab.air.extensions.pdf.PdfViewer;
import com.myflashlab.air.extensions.pdf.PdfViewerEvent;
import flash.filesystem.*; 

var _ex:PdfViewer = new PdfViewer();
_ex.addEventListener(PdfViewerEvent.STATUS, onStatus);

var result:Boolean = _ex.run(File.documentsDirectory.resolvePath("LISTE PAV DEEE 2018.pdf"));
trace(result);

 function onStatus(e:PdfViewerEvent):void
{
	trace(e.param);
}

```

But it's throwing this error : 

```
ReferenceError = ReferenceError: Error #1065: Variable OverrideAir is not defined.
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.pdf::PdfViewer()
	at Sansnom_1_fla::MainTimeline/frame1()[Sansnom_1_fla.MainTimeline::frame1:5]
```

Line 5 is : `var _ex:PdfViewer = new PdfViewer();`

Here's my xml file : 

```
-<application xmlns="http://ns.adobe.com/air/application/28.0">
<id>Sansnom1</id>
<versionNumber>1.0.0</versionNumber>
<versionLabel/>
<filename>Sans nom-1</filename>
<description/>
<name>Sans nom-1</name>
<copyright/>
-<initialWindow>
<content>Sans%20nom-1.swf</content>
<systemChrome>standard</systemChrome>
<transparent>false</transparent>
<visible>true</visible>
<fullScreen>false</fullScreen>
<aspectRatio>portrait</aspectRatio>
<renderMode>cpu</renderMode>
<autoOrients>false</autoOrients>
</initialWindow>
<icon/>
<customUpdateUI>false</customUpdateUI>
<allowBrowserInvocation>false</allowBrowserInvocation>
-<extensions>
<extensionID>com.myflashlab.air.extensions.pdfViewer</extensionID>
</extensions>
</application>

```

What could be the problem ?

**Comment by myflashlab** [comment]
Try checking the sample project we have on Github, the sample manifest file here https://github.com/myflashlab/PDF-ANE/blob/master/AIR/Main-app.xml#L103-L113 shows that you need to add some ANE dependencies. the overrideAIR and the androidsupport ANEs can be found here:  https://github.com/myflashlab/common-dependencies-ANE

On Android, especially when you want to open a PDF on ```File.documentsDirectory```, you will need storage permission which the permission ANE can help you wish that. http://www.myflashlabs.com/product/native-access-permission-check-settings-menu-air-native-extension/

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
