### ISSUE TITLE
Is it supposed to load the PDF? or share it?

### ISSUE THREAD

**Issue by thatkidrich** [myflashlab/PDF-ANE#15]
The PDF doesn't open, it just brings up the share box to send to other applications

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
