### ISSUE TITLE
PDF Viewer?  Why can't I View ?

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/PDF-ANE#16]
I've implemented it but all it does is open a confusing iOS dialog with options like "Copy to DropBox"  ..   I bought this to be able to click on a button and view the PDF.  Can this not be done?  If so... how ?

Any help is appreciated.

**Comment by myflashlab** [comment]
The ANE allows you to open a pdf file in an app which can read PDFs. this is clearly mentioned at the first page of our GitHub:
> Pdf Viewer Air Native Extension lets you open pdf files right from your Air mobile apps. On both Android and iOS, it will open a dialog and lets you select which program you wish to use for opening the file.

However, there are other options you may try, read this post for example: https://www.myflashlabs.com/how-to-open-parse-pdf-using-richwebview-ane/

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
