### ISSUE TITLE
Variable OverrideAir is not defined

### ISSUE THREAD

**Issue by miso7043** [myflashlab/PDF-ANE#17]
I ask something by email about that it is possible for my project or not 

you answer that it is possible, so I bought this ane.

but It is not work from the first step.
Can I get some help or refund my money?

----------------------------------------------------------------------------------------
My code is
```actionscript
package  {
	import flash.display.Sprite;
	import flash.filesystem.File;
	
	import com.myflashlab.air.extensions.pdf.*;
	
	
	public class Main extends Sprite {		
			
		public function Main() {
			// constructor code
			var _ex:PdfViewer = new PdfViewer();
			_ex.addEventListener(PdfViewerEvent.STATUS, onStatus);
			
			trace(_ex.run(File.applicationDirectory.resolvePath("sample_pdf.pdf")));
     
		}
		
		private function onStatus($e:PdfViewerEvent):void
		{
			trace($e.param);
		}
	}
}
```
----------------------------------------------------------------------------------------
below is error msg.
```
ReferenceError = ReferenceError: Error #1065: Variable OverrideAir is not defined.
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.pdf::PdfViewer()
	at Main()[D:\PDF Reader ANE\Main.as:12]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()
```

**Comment by myflashlab** [comment]
> Can I get some help or refund my money?

tickets on GitHub are tech related, for other things, you need to [contact our team directly](http://www.myflashlabs.com/contact/). Besides, Your sentence seems like a mild threat. I have already been warned by my supervisor to report to him if I see such tech-unrelated threats!

About your code, well, have you checked the [sample codes](https://github.com/myflashlab/PDF-ANE/blob/master/AIR/src/MainFinal.as) or [docs](https://github.com/myflashlab/PDF-ANE#air-usage) at all? Are you testing on iOS or Android? Are you using the latest AIR SDK?

Besides, the ```OverrideAIR``` error means you have not included the overrideAIR ANE.   
https://github.com/myflashlab/PDF-ANE/tree/master/AIR/lib   
https://github.com/myflashlab/PDF-ANE/blob/master/AIR/Main-app.xml#L114-L122

**Comment by miso7043** [comment]
![ane](https://user-images.githubusercontent.com/41462799/42988686-c190bd98-8c27-11e8-9722-1e79d0edbda8.jpg)

I add ane file. 

I check about this
trace(OverrideAir.isSupported)
return is false.

and I use my code as below 
			var _ex:PdfViewer = new PdfViewer();
			_ex.addEventListener(PdfViewerEvent.STATUS, onStatus);
			trace(_ex.run(File.applicationDirectory.resolvePath("sample_pdf.pdf")));

error is 
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.pdf::Launcher/run()
	at com.myflashlab.air.extensions.pdf::PdfViewer/run()
	at Main()[D:\PDF Reader ANE\Main.as:31]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

What should I do?
I just want to make simple PDF viewer for desktop computer.
But my client doesn't want to use the javascript.

Can I have a simple soulution?

**Comment by myflashlab** [comment]
**desktop**?! We don't build ANEs for desktop. We have never built for desktop. Only Android and iOS. This is clearly mentioned everywhere. https://github.com/myflashlab/PDF-ANE#pdf-viewer-ane-v221-androidios
