### ISSUE TITLE
 pdf not loaded  the return value is false (android) 

### ISSUE THREAD

**Issue by moazatiani** [myflashlab/PDF-ANE#18]
hi , when i use pdf ane and follow your steps you provided  and after i tested in my android device the pdf not loaded and the value return false , on the other hand how to set the pdf file on cache directory may be this is the problem so please how to solve this issue 

best regards

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
