### ISSUE TITLE
Can not Open PDF

### ISSUE THREAD

**Issue by kinjal111** [myflashlab/PDF-ANE#2]
Hello, Please Look at attached image.  i was tried open pdf using following code.
can not see pdf.can you please help me with that issue?

var _ex:PdfViewer = new PdfViewer();
_ex.addEventListener(PdfViewerEvent.STATUS, onStatus);
var destination:File = File.applicationStorageDirectory;  
var source:File = File.applicationDirectory.resolvePath("pdf");
source.copyTo(destination, true);
trace(_ex.run(File.applicationStorageDirectory.resolvePath("ReadMe.pdf"))); // can see value true in output]

function onStatus(e:PdfViewerEvent):void
{
    trace(e.param);
}

![5403ce6ffda793c205edd8bb4477d4a1e6d8509520e3820c9c pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/13674937/12843503/cdbce06c-cc1f-11e5-86ab-fecaca89e4e8.jpg)

**Comment by myflashlab** [comment]
The first thing I'm noticing is that you are trying to open a pdf with name of ReadMe.pdf but the toast message in your screenshot says demo.pdf. So, I'm confused here!

besides that, our ANE is never supposed to show a toast. so, my guess is that you have an application which is supposed to open pdf files but it actually can't open it? are you able to provide us with more details please?

**Comment by kinjal111** [comment]
Hello, i was tested with two pdf. its my mistake i sent you image of my second test with demo.pdf and i past code here for ReadMe.pdf. it can not open pdf.

**Comment by myflashlab** [comment]
As suggested in my last message, it's either because you tried to open the pdf with a program which is supposed to open pdf files but it doesn't.

if that is not the case, then it means there is no application to be able to open pdf files. this is when you should promote your user to download one from Google Play store. like Adobe Acrobat.

Are you receiving the ```onOpen``` or ```onClose``` events?

**Comment by kinjal111** [comment]
yes,i am receiving event.. getting following in output. it displays path too
Output:
Waiting for Player to connect...
[SWF] PDFDemo.swf - 1337 bytes after decompression
url :: file:/data/data/air.PDFDemo/PDFDemo/Local Store/ReadMe.pdf
true
onOpen
onClose

**Comment by kinjal111** [comment]
then after just trace 'onClose' event i can see this image state on my phone.
![img](https://cloud.githubusercontent.com/assets/13674937/12879442/074f0cf2-ce59-11e5-9afc-b565fc1f3d07.jpg)

**Comment by myflashlab** [comment]
aha, I think I got the problem. please read here: https://github.com/myflashlab/PDF-ANE#tech-details
you can't use ```File.applicationStorageDirectory``` on Android for opening pdf files.

**Comment by kinjal111** [comment]
see when i was tried with like that 'trace(_ex.run(File.applicationDirectory.resolvePath("ReadMe.pdf")));' then it give me false. i already attached my PDF file in .fla.

**Comment by myflashlab** [comment]
I know! please read the information here more carefully: https://github.com/myflashlab/PDF-ANE#tech-details

> On Android side, you cannot open a pdf file in another app unless the pdf file is somewhere public. which means your file must be copied into File.documentsDirectory before you can open it

**Comment by kinjal111** [comment]
Hello, thanks now i can see and open pdf

**Comment by kinjal111** [comment]
one more question, right now it open in new pdf viewer window.
when we click on back button , we will come back at our app directly. but why we can not open pdf inside app itself?

**Comment by myflashlab** [comment]
This feature will be added to the ANE in future versions.

**Comment by kinjal111** [comment]
okay
