### ISSUE TITLE
App crashes when used with Adobe AIR 22 Beta

### ISSUE THREAD

**Issue by MaartenWeber** [myflashlab/PDF-ANE#4]
Hello,

Since Air 22 Beta fixed an issue that prevented apps to be submitted to the App Store I updated my Air version to 22. However, every time I try to open a pdf, my app crashes. When I restored my previous Air SDK to version 20 it worked like a charm again.

Could it be that the new Air 22 that is in Beta causes the NativeExtension to crash?
I've tested it on an iPad 4 and an iPhone 5S.

Thanks in advance!

Kind regards,

Maarten

**Comment by myflashlab** [comment]
We have not tested the ANE with the 22 Beta version yet but tell me if you have this problem with Air 21 also?

**Comment by MaartenWeber** [comment]
I've tested it with the latest release version 21 and it still works with that one. Though as soon as I use 22 it crashes. Normally I wouldn't use the beta version, though with this version an inportant issue is fixed.

Could you test it with 22 as well so I can be sure it's not just me? :)

Thanks!

**Comment by MaartenWeber** [comment]
Hey hey,

Have you been able to test the extension with Air 22 yet?

Thanks in advance!

**Comment by myflashlab** [comment]
we wonder if you are still having such a problem with the latest version of the ANE?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
