### ISSUE TITLE
Problem running ANE on android device

### ISSUE THREAD

**Issue by amol-pandhare** [myflashlab/PDF-ANE#5]
I have followed the video that myFlashLabs have for using the ANE with Flash builder. I also refered to the github link for the PDF ANE for settings to be incorporated. I have the common-dependencies ANE also added to the project. I have even tried using the SWC instead of the ANE's that are provided in the package. Following is the screenshot of the error I get when debugging on the android device. 

The error comes on the very first line of the code from the following sniplet that I have used:
import com.myflashlab.air.extensions.pdf.PdfViewer;
import com.myflashlab.air.extensions.pdf.PdfViewerEvent;

var _ex:PdfViewer = new PdfViewer();
_ex.addEventListener(PdfViewerEvent.STATUS, onStatus);

var result:Boolean = _ex.run(File.documentsDirectory.resolvePath("sample_pdfViewer_ane.pdf"));
trace(result);

private function onStatus(e:PdfViewerEvent):void
{
	trace(e.param);
}

Inline image 1
![image](https://cloud.githubusercontent.com/assets/14179656/25374307/7ac7b590-29ba-11e7-918d-1c4ff00aa724.png)

My project settings use SDK 4.6 fused with AIR sdk 16. The ANE's are added to project settings and also to android build packaging settings. I get a dependency conflict trying to include all the 3 ANEs for the packaging for android. Following is the screenshot for the same.

Inline image 2
![image](https://cloud.githubusercontent.com/assets/14179656/25374325/90d1272c-29ba-11e7-962a-a838f5ac7cbe.png)

I have even tried using the SDK 4.16 with AIR SDK 23 by downloading it on my machine and compiling it with the newer SDK. I still get the same problems as indicated abov

**Comment by myflashlab** [comment]
1) you are not trying to run the ANE on a simulator, are you?
2) Do you have other ANEs from other ANE providers in your project also?

**Comment by amol-pandhare** [comment]
> > you are not trying to run the ANE on a simulator, are you?

I am trying to run it on the device, not on simulator, when i get those errors.

> > Do you have other ANEs from other ANE providers in your project also?

Nope

**Comment by myflashlab** [comment]
Ok, Please post your manifest .xml file so we can have a look and see if there's anything missing there.

**Comment by amol-pandhare** [comment]
[manifest file.zip](https://github.com/myflashlab/PDF-ANE/files/955138/manifest.file.zip)
Attached is the manifest .xml file as a zip. Looking forward to hear from you.

**Comment by myflashlab** [comment]
hmm, the manifest .xml file looks fine. you know, for some reason your IDE is not correctly finding the ANE. If it had, it wouldn't had thrown the null object reference error message. Ok, try this: Update your AIR SDK from 16 to 25. 16 is way too old anyhow. And while doing that, make sure to target AIR 25 or 24 in your manifest instead of 16.

**Comment by amol-pandhare** [comment]
I tried with both the AIR SDK's 23 and 24.. I still get the same problem. I am using Flash builder 4.6. For some reasons AIR sdk 25 never worked properly when manually updated my sdk . Also tried the Apache Flex installer to get the AIR sdk 25 but the downloads fails midway everytime. I checked on multiple machines as well. Would it be possible to share a configured working project, that uses PDF ANE?

Would really appreciate your help on this. I even tried the demo ANE. Even that also gave me the same issues i indicated in my first post.

**Comment by amol-pandhare** [comment]
Well I somehow got the ANE to work using the AIR SDK 23, but I always get false at the following line of code:
var result:Boolean = _ex.run([File Object]);
trace(result);

The trace returns me 'false', even when debugging I get the path of the file correctly and it exist on the device at that location.

**Comment by amol-pandhare** [comment]
I am calling files from the documentDirectory of Android device.

**Comment by myflashlab** [comment]
The file object must be a pdf file (with the pdf extension). like this ```var result:Boolean = _ex.run(File.documentsDirectory.resolvePath("sample_pdfViewer_ane.pdf"));``` If the file exists, that method should not return false!

**Comment by amol-pandhare** [comment]
It is a pdf extension. Still its returning false and I have PDF apps on my device as well. The Demo apk works correctly on my device. I am using the same device to debug.

File.documentsDirectory.resolvePath("Test_report.pdf");

I have this file on my device on the location. But the I dont get the menu where it shows the apps to use t open the PDF file on the device. As the following statement always returns false.
var result:Boolean = _ex.run(File.documentsDirectory.resolvePath("Test_report.pdf"));

**Comment by myflashlab** [comment]
Hmm, try this: If you are using the demo ANE, make sure you are not calling the ```_ex.run(File.documentsDirectory.resolvePath("Test_report.pdf"));``` immediately after initializing the ANE.

The ```run``` method work only if you have already closed the demo dialog. Let us know how it goes.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
