### ISSUE TITLE
Wondering how i open a pdf from a url?

### ISSUE THREAD

**Issue by dgurney75** [myflashlab/PDF-ANE#7]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version:
* iOS Version:
* AIR SDK Version:

## Problem Description ##
Describe your problem in detail.
* Copy your manifest ```.xml``` file.
```xml
<my><manifest/></my>
```
* Copy your Actionscript code.
```actionscript
var myScript:AS;
```

## Steps to Reproduce ##
Tell us how this issue can be reproduced.

## Known Workarounds ##
Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by myflashlab** [comment]
https://www.myflashlabs.com/how-to-open-parse-pdf-using-richwebview-ane/
