### ISSUE TITLE
Demo alert shows on paid PDF ANE

### ISSUE THREAD

**Issue by kanding** [myflashlab/PDF-ANE#8]
![pdfane](https://user-images.githubusercontent.com/313359/30701247-13047baa-9eea-11e7-8d09-7932c31a1b29.png)

## Environment ##
* Android API Version: N/A
* iOS Version: Latest on iPad
* AIR SDK Version: 27

## Manifest file ##
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/27.0">
  <id>com.mediamedic.decanter</id>
  <versionNumber>1.0</versionNumber>
  <filename>EP_TEST</filename>
  <description/>
  <!-- To localize the description, use the following format for the description element.
	<description>
		<text xml:lang="en">English App description goes here</text>
		<text xml:lang="fr">French App description goes here</text>
		<text xml:lang="ja">Japanese App description goes here</text>
	</description>
	-->
  <name>EP_TEST</name>
  <!-- To localize the name, use the following format for the name element.
	<name>
		<text xml:lang="en">English App name goes here</text>
		<text xml:lang="fr">French App name goes here</text>
		<text xml:lang="ja">Japanese App name goes here</text>
	</name>
	-->
  <copyright/>
  <initialWindow>
    <content>P1_P2_P3_ipad.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <autoOrients>false</autoOrients>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>auto</renderMode>
    <maximizable>true</maximizable>
    <minimizable>true</minimizable>
    <resizable>true</resizable>
  </initialWindow>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <icon>
    <image48x48>grafik/icons/iPad/AL_icon48.png</image48x48>
    <image72x72>grafik/icons/iPad/AL_icon72.png</image72x72>
    <image50x50>grafik/icons/iPad/AL_icon50.png</image50x50>
  </icon>
  <iPhone>
    <requestedDisplayResolution>high</requestedDisplayResolution>
    <InfoAdditions><![CDATA[
  <key>UIDeviceFamily</key>
  <array>
    <string>2</string>
  </array>
  <key>MinimumOSVersion</key>
  <string>8.0</string>
  <key>UIStatusBarStyle</key>
  <string>UIStatusBarStyleBlackOpaque</string>
  <key>UIRequiresPersistentWiFi</key>
  <string>NO</string>
]]></InfoAdditions>
  </iPhone>
  <supportedLanguages>en</supportedLanguages>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.pdfViewer</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
  </extensions>
</application>
```

## Copy your Actionscript code. ##
* See attached PNG

## Steps to Reproduce ##
I started with the demo. The demo alerted "You are using the demo version..." at start up of the app. And further when clicking the button that would launch the PDF.

I bought the ANE, and downloaded it from the purchase mail. Removed the demo version and added the new one.
It still alerts me at start up, but otherwise works.
Ive included the ANEs the readMe files tells me it needs. But I dont know if there's any conflict.

Heres a link to a dropbox containing the project. 

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Please note that I've removed some films, so click only on the button called [ 360 ]. It should launch the PDF

Cheers

John

**Comment by myflashlab** [comment]
1. NEVER share ANY of MyFlashLabs ANEs in public. This is strongly against the rules. Read here: https://www.myflashlabs.com/licensing/ I understand that it was not intentional. It could have caused you permanent ban from using our products.

2. besides the pdf ANE, you are also using the ```com.myflashlab.air.extensions.permissionCheck``` ANE, make sure you are using the licensed version of that ANE also. I checked and saw that the demo dialog opens because you are using a demo version of the permissioncheck ANE.

**Comment by kanding** [comment]
Ouups, sorry. Didnt think of that. The link has been removed. Thanks, for the reply. Ill try that and it problaby the reason
