### ISSUE TITLE
The pdf doesn't open and the file exists

### ISSUE THREAD

**Issue by ggcatalin** [myflashlab/PDF-ANE#9]
## Environment ##
* iOS Version: 11
* AIR SDK Version: 27

## Problem Description ##
I bought (today 05-oct-2017) the PDF Reader ANE (Android+iOS) and I want to open a pdf file stored in applicationStorageDirectory and the file is not opening, and the app tries to open that Share Helper (like in the screenshots).
I put in my code to check if the file exists and the file.url and it should work. 

The screenshots:
https://www.dropbox.com/s/h077t53wzy8dv0t/%5E6DED51F77A1BAC0925E285332D4969FCDF4E4E6FD9F6D89735%5Epimgpsh_fullsize_distr.jpg?dl=0
https://www.dropbox.com/s/6d5y2a38e3xn4kx/%5E21D24199D98A10E9DEB13B8D3EF511C772F18BF8FE56817655%5Epimgpsh_fullsize_distr.jpg?dl=0

I am trying to install the webView ANE as well (the demo version) and it is now working either, I tried the google.com page, a jpg file from the StorageDirectory and a mp4. Neither worked. What am I doing wrong? 

Thank you!

I have this xml in my 
```xml
<iPhone><InfoAdditions> 
<key>UIDeviceFamily</key>
<array>
    <string>1</string>
    <string>2</string>
</array>
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true />
</dict>
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleBlackOpaque</string>
<key>UIRequiresPersistentWiFi</key>
<string>NO</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>I need location when in use</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>I need location always</string>
```
And the extensions:
```xml
<extensions>
    <extensionID>com.myflashlab.air.extensions.pdfViewer</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.webView</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
  </extensions>
```
* Copy your Actionscript code.
```actionscript
//fileName is a string with the file stored in applicationStorageDirectory
var file : File = File.applicationStorageDirectory;
file.nativePath = file.nativePath + "/" + fileName;
var path : String = file.nativePath;
_ex = new PdfViewer();
_ex.addEventListener(PdfViewerEvent.STATUS, onStatus);
//the log events that you see in the screenshot
var dispatcherx : LogEvents = new LogEvents(LogEvents.LOG_EVENT, "PDF EXISTS - " + String(file.exists));
dispatchEvent(dispatcherx);
dispatcherx = new LogEvents(LogEvents.LOG_EVENT, "PDF PATH - " + String(file.url));
dispatchEvent(dispatcherx);

_ex.run(file);
function onStatus(e : PdfViewerEvent) : void {
  trace(e.param);
}
```

**Comment by myflashlab** [comment]
The first thing that I noticed was how how you are addressing the file object. maybe the easier way was to do it like this:

```actionscript
var file:File = File.applicationStorageDirectory.resolvePath(fileName);
```

Another thing is that if you are using the demo version of the ANE, you must not call any ANE methods before you close the demo dialog. If you have purchased a license, make sure you are using the licensed ANE.

And finally, put a trace on ```_ex.run(file);``` and tell me what result does the ```run``` method returns.

**Comment by ggcatalin** [comment]
Hello,
Thank you for responding, I just tried the suggested code for the File and didn't work, the issue is the same, the _ex.run(file); is saying true. I have the licensed ANE, I don't have the message with the Demo version. I don't get why it is opening the Sharing / Helper box with Airdrop / Save files ... like it was in that screenshot. Do I need to add some permissions using the permissionCheck ANE?
Catalin 

    On Friday, October 6, 2017 11:21 AM, MyFlashLabs <notifications@github.com> wrote:
 

 The first thing that I noticed was how how you are addressing the file object. maybe the easier way was to do it like this:var file:File = File.applicationStorageDirectory.resolvePath(fileName);Another thing is that if you are using the demo version of the ANE, you must not call any ANE methods before you close the demo dialog. If you have purchased a license, make sure you are using the licensed ANE.And finally, put a trace on _ex.run(file); and tell me what result does the run method returns.—

**Comment by myflashlab** [comment]
Oh, you are seeing the dialog, well, when the dialog opens, it lets you specify the app with which you'd like to open the pdf file. check this out: https://github.com/myflashlab/PDF-ANE#tech-details

Besides that, you may find this blog post useful also: http://www.myflashlabs.com/how-to-open-parse-pdf-using-richwebview-ane/

**Comment by ggcatalin** [comment]
Ha! So, your ANE is just opening the file with an external app that can read the pdf. :) It is my mistake, I read what I wanted to know. Anyway, you are telling me to use the reachwebview, does it work with the files from applicationStorage?

**Comment by myflashlab** [comment]
yes, on Android and iOS, it is using third party apps to open PDF files. The Acrobat reader app is probably the best candidate for this job.

We have not tested RichWebView with local PDF files as it has not been its main job anyhow and that blog post was just a workaround for those who need to open pdf files directly in their app. Maybe you can test that with the [demo ANE](https://github.com/myflashlab/webView-ANE/) available prior to purchasing it.

If it works already, that's good news, if not, let me know and we are interested to make that happen with an upgrade on the ANE :D If possible, we'll do it.
